apiVersion: apps/v1
kind: Deployment
metadata:
  name: masterchief
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: masterchief
  template:
    metadata:
      labels:
        app: masterchief
    spec:
      containers:
        - image: loonison101/masterchief:v2
          name: masterchief
          ports:
            - containerPort: 3000
          env:
            - name: ESDB_CONN
              value: esdb://admin:changeit@casgnclo0aeqbb9hn23g.mesdb.eventstore.cloud:2113
            - name: NEXT_PUBLIC_API_URL
              value: http://test.local
