import { UserProvider } from '@auth0/nextjs-auth0/client';
import './global.css';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/*      <head>*/}
      {/*        <link*/}
      {/*          href="*/}
      {/*https://dohliam.github.io/dropin-minimal-css/min/axist.min.css"*/}
      {/*          rel="stylesheet"*/}
      {/*        />*/}
      {/*      </head>*/}
      <UserProvider>
        <body>{children}</body>
      </UserProvider>
    </html>
  );
}
