config:
  lkat-infrastructure:didYouAdventureForm:
    secure: AAABAIyvs+g0bqDb2enuVowBG8aIchqB85NaNdI0ImX+qKaLBe8rC439ujxzSNMuTiNIIBRGZMvZFVDPp0+t0uBjlTQjoqdtAfaIu7fd2yfqZtDRwqgspOKGxLtDPQAeoxUX6KWPUaPoPMNlrXylWCdh
