// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: all.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LkatService_Ping_FullMethodName = "/LkatService/Ping"
)

// LkatServiceClient is the client API for LkatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LkatServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
}

type lkatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLkatServiceClient(cc grpc.ClientConnInterface) LkatServiceClient {
	return &lkatServiceClient{cc}
}

func (c *lkatServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, LkatService_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LkatServiceServer is the server API for LkatService service.
// All implementations must embed UnimplementedLkatServiceServer
// for forward compatibility
type LkatServiceServer interface {
	Ping(context.Context, *PingRequest) (*PongResponse, error)
	mustEmbedUnimplementedLkatServiceServer()
}

// UnimplementedLkatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLkatServiceServer struct {
}

func (UnimplementedLkatServiceServer) Ping(context.Context, *PingRequest) (*PongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLkatServiceServer) mustEmbedUnimplementedLkatServiceServer() {}

// UnsafeLkatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LkatServiceServer will
// result in compilation errors.
type UnsafeLkatServiceServer interface {
	mustEmbedUnimplementedLkatServiceServer()
}

func RegisterLkatServiceServer(s grpc.ServiceRegistrar, srv LkatServiceServer) {
	s.RegisterService(&LkatService_ServiceDesc, srv)
}

func _LkatService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LkatServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LkatService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LkatServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LkatService_ServiceDesc is the grpc.ServiceDesc for LkatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LkatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LkatService",
	HandlerType: (*LkatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _LkatService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "all.proto",
}
