apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  namespace: default
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: minio-pv
          persistentVolumeClaim:
            claimName: minio-pv-claim
      containers:
        - image: bitnami/minio:latest
          name: minio
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - mountPath: /data
              name: minio-pv
          env:
            - name: MINIO_ROOT_USER
              value: minio-root-user
            - name: MINIO_ROOT_PASSWORD
              value: minio-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: minio-http
      port: 9000
      targetPort: 9000
    - name: minio-grpc
      port: 9001
      targetPort: 9001
