apiVersion: v1
kind: Service
metadata:
  name: masterchief
  namespace: default
spec:
  type: NodePort
  selector:
    app: masterchief
  ports:
    - name: http
      port: 3000
      targetPort: 3000
