// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgenerated

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ModelsObsidianTag struct {
	Tag     pgtype.Text
	MaxDate pgtype.Date
}
