/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ChooseEventType = PersonalRecordClimbingData | MaintenanceCreatedData | AdventureCreatedData;
export type Name = string;
export type Date = string;
export type EventNames = "personal-record-climbing-created" | "maintenance-created" | "adventure-created";
export type Name1 = string;
export type Date1 = string;
export type EventNames1 = "personal-record-climbing-created" | "maintenance-created" | "adventure-created";
export type Name2 = string;
export type Date2 = string;
export type Activities =
  | "backpacking"
  | "ball-golf"
  | "basketball"
  | "beach-pong"
  | "beer-pong"
  | "boat-tubing"
  | "bowling"
  | "camper-camping"
  | "camping"
  | "concert"
  | "cornhole"
  | "dh-mountain-biking"
  | "disc-golf"
  | "drinking-alcohol"
  | "escape-room"
  | "family-time"
  | "fishing"
  | "flag-football"
  | "fly-fishing"
  | "frisbee"
  | "hiking"
  | "horseshoes"
  | "hunting"
  | "indoor-bouldering"
  | "indoor-rope-climbing"
  | "indoor-trampoline-park"
  | "kayaking"
  | "life-event"
  | "maitenance"
  | "mountain-biking"
  | "movie-theatre"
  | "museum"
  | "outdoor-rock-climbing"
  | "overlanding"
  | "paintball"
  | "putt-putt-golf"
  | "road-biking"
  | "road-trip"
  | "snowboarding"
  | "softball"
  | "swimming"
  | "tennis"
  | "theme-park"
  | "volleyball"
  | "water-park"
  | "white-water-rafting";
export type EventNames2 = "personal-record-climbing-created" | "maintenance-created" | "adventure-created";

export interface PersonalRecordClimbingData {
  name: Name;
  date: Date;
  eventName: EventNames;
}
export interface MaintenanceCreatedData {
  id: string;
  name: Name1;
  date: Date1;
  eventName: EventNames1;
}
export interface AdventureCreatedData {
  name: Name2;
  date: Date2;
  activities: Activities;
  eventName: EventNames2;
}
