builds:
  - id: lk
    binary: lk
    main: './cmd/lk'
    goos:
      - linux
      - windows
    goarch:
      - amd64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip