version: "3.5"
services:
  postgresql:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data