apiVersion: apps/v1
kind: Deployment
metadata:
  name: masterchief-deployment
  labels:
    app: masterchief
spec:
  replicas: 1
  selector:
    matchLabels:
      app: masterchief
  template:
    metadata:
      labels:
        app: masterchief
    spec:
      containers:
        - name: masterchief-container
          image: loonison101/masterchief:5f9bc110695f311323d33f34f808a73856384d35
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          env:
            - name: ESDB_CONN
              value: esdb://admin:changeit@esdb-eventstore:1113
