apiVersion: apps/v1
kind: Deployment
metadata:
  name: masterchief
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: masterchief
  template:
    metadata:
      labels:
        app: masterchief
    spec:
      containers:
        - image: loonison101/masterchief:c53021141fe3639168b48b813f2f87ff6d9aeaf5
          imagePullPolicy: Always
          name: masterchief
          ports:
            - containerPort: 3000
          env:
            - name: ESDB_CONN
              value: esdb://esdb:2113?tls=false
            - name: NEXT_PUBLIC_API_URL
              value: http://mc.lanekatris.com
            - name: MINIO_URL
              value: minio
            - name: MINIO_PORT
              value: '9000'
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mc-secret
                  key: password
                  optional: false
            - name: HOME_LATITUDE
              valueFrom:
                secretKeyRef:
                  key: home_latitude
                  name: mc-secret
                  optional: false
            - name: HOME_LONGITUDE
              valueFrom:
                secretKeyRef:
                  key: home_longitude
                  name: mc-secret
                  optional: false
            - name: ELASTIC_URL
              valueFrom:
                secretKeyRef:
                  key: elastic_url
                  name: mc-secret
                  optional: false
            - name: VITE_GRAPHQL_URL
              value: https://lanekatris.com/graphql
