const csv=require('csvtojson')
const fs = require('fs')

function p(line){
    return `| ${line} |`
}

function c(line){
    return line.replace(/\n/g, '').replace(/\|/g, '')
}

function u(line) {
    return `[Link](${line})`
}

function i(line){
    return `![](${line})`
}

function d(line){
    const date = new Date(Date.parse(line))
    return `${date.toLocaleDateString()} ${date.toLocaleTimeString()}`
}

const date = '2023-06-03'
const sourceFile = `../../data/raindrop-source-${date}.csv`
const targetGeneratedFile = `../../data/raindrop-generated-${date}.json`
const targetObsidianFile = 'C:\\Users\\looni\\OneDrive\\Documents\\vault1\\Public\\Raindrop IO.md'
const publicUrlPrefix = 'https://github.com/lanekatris/monorepo'
const columns = ['title', 'description','url','folder','tags','created']

async function go() {
    const jsonArray=await csv().fromFile(sourceFile);
    jsonArray.sort((a,b) => Date.parse(b.created) - Date.parse(a.created))
    console.log(jsonArray[0])
    const headers = Object.keys(jsonArray[0]).filter(x => columns.includes(x)).map(x => x.charAt(0).toUpperCase() + x.slice(1))
    const fileArray = [
        `**Updated**: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 
        '', 
        `> You can go [here](${publicUrlPrefix}/tree/main/data) to view raw data files in various formats that start with \`raindrop*\``, 
        '',  
        `> This file was generated by [this code](${publicUrlPrefix}/blob/main/software/bookmark-io/index.js)`,
        '',
        p(headers.join('|'))]
    const belowHeaders = Array.from({length: headers.length}, (v, i) => '---').join('|')
    fileArray.push(p(belowHeaders))

    jsonArray.forEach(x => {
        const idk = [c(x.title),c(x.description),u(x.url),x.folder,x.tags,d(x.created)]
        fileArray.push(p(idk.join('|')))
    })

    const fileContents = fileArray.join('\n')
    fs.writeFileSync(targetObsidianFile, fileContents)
    fs.writeFileSync(targetGeneratedFile, JSON.stringify(jsonArray, null, 2))
}

go();

