---
- hosts: homelab
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          - htop
          - vim
          - curl
          - ranger
          - ansible
          - sshpass